In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as np
import seaborn as sns
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel

In [2]:
df=pd.read_csv("dice_com-job_us_sample.csv")
df.head(1)

,advertiserurl,company,employmenttype_jobstatus,jobdescription,jobid,joblocation_address,jobtitle,postdate,shift,site_name,skills,uniq_id
0,https://www.dice.com/jobs/detail/AUTOMATION-TE...,"Digital Intelligence Systems, LLC","C2H Corp-To-Corp, C2H Independent, C2H W2, 3 M...",Looking for Selenium engineers...must have sol...,Dice Id : 10110693,"Atlanta, GA",AUTOMATION TEST ENGINEER,1 hour ago,Telecommuting not available|Travel not required,NaN,SEE BELOW,418ff92580b270ef4e7c14f0ddfc36b4

In [3]:
df.shape

(22000, 12)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22000 entries, 0 to 21999
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   advertiserurl             22000 non-null  object
 1   company                   21950 non-null  object
 2   employmenttype_jobstatus  21770 non-null  object
 3   jobdescription            22000 non-null  object
 4   jobid                     22000 non-null  object
 5   joblocation_address       21997 non-null  object
 6   jobtitle                  22000 non-null  object
 7   postdate                  22000 non-null  object
 8   shift                     21643 non-null  object
 9   site_name                 3490 non-null   object
 10  skills                    21957 non-null  object
 11  uniq_id                   22000 non-null  object
dtypes: object(12)
memory usage: 2.0+ MB

In [5]:
df.dropna(inplace=True)
df["jobtitle"].head(15)

96                           (US)-Program Manager Senior
97     Business Analyst - Mortgage/Equiting Lending, ...
98        DHMSM Operational Medicine Interface Developer
99                      Information Technology Architect
100                           SWIFT Messaging Specialist
101                                   Technician-Systems
102       Angular JS / SOA / Web Developer w/ Middleware
104                Soarian Clinicals Consultant (Cerner)
106                                       Java Developer
107                        SQL Web Application Developer
108                           Mobile Device QA Tester II
109                       Processor (Screen) - 3rd Shift
110                           Sr. Application Programmer
111                                 Full Stack Developer
112                      Technology Manager of Analytics
Name: jobtitle, dtype: object

In [6]:
df.shape

(3417, 12)

In [7]:
tfidf=TfidfVectorizer(stop_words="english")
df["jobdescription"]=df["jobdescription"].fillna('')

In [8]:
clean=pd.read_csv("cleaned_skills.csv")
clean.head()

                                      cleaned_skills
0                     swift ios swift ios atom xcode
1  javascript python ruby sql .net core mysql sql...
2  java php python mysql c python rust sublime te...
3  matlab python r sql react mongodb redis sql se...
4  javascript php rust mysql linux desktop amazon...

In [9]:
final_data = pd.merge(df, clean, left_index=True, right_index=True)

In [10]:
final_data.head()

,advertiserurl,company,employmenttype_jobstatus,jobdescription,jobid,joblocation_address,jobtitle,postdate,shift,site_name,skills,uniq_id,cleaned_skills
96,https://www.dice.com/jobs/detail/%2528US%2529%...,Princeton Information Ltd,"Full Time, FULL_TIME",Responsible for managing one or more highly co...,Dice Id : cxprince,"Woodland Hills, CA",(US)-Program Manager Senior,5 hours ago,Telecommuting not available|Travel not required,www.dice.com,"Access, Application, Business Requirements, CA...",a560c9c03ec3eb3dbf9fa881303fdf48,java javascript lua php r sql react spark post...
97,https://www.dice.com/jobs/detail/Business-Anal...,SMCI,"Contract W2, 5",Job Description: Seeking a Business Process An...,Dice Id : 10301550,"Los Angeles, CA","Business Analyst - Mortgage/Equiting Lending, ...",5 hours ago,Telecommuting not available|Travel not required,www.dice.com,"Mortgage/Equiting Lending, Lean Six Sigma Gree...",0445fcb37ab17f686c025da15a98de52,c++ c java react .net core windows desktop clo...
98,https://www.dice.com/jobs/detail/DHMSM-Operati...,"TAD PGS, Inc","Contract W2, 12 Months","TAD PGS, INC. is currently seeking a DHMSM Ope...",Dice Id : 10285720a,"Vienna, VA",DHMSM Operational Medicine Interface Developer,5 hours ago,Telecommuting not available|Travel not required,www.dice.com,"TAD PGS, INC. specializes in delivering secure...",f3454168b74bc184e99b6d328970c16d,c java javascript python sql node.js .net core...
99,https://www.dice.com/jobs/detail/Information-T...,Mitchell Martin,"Contract Corp-To-Corp, Contract Independent, C...","Our client, one of the world's leading profess...",Dice Id : mitchmar1,"Alpharetta, GA",Information Technology Architect,5 hours ago,Telecommuting not available|Travel not required,www.dice.com,"Analysis, Architecture, Business Requirements,...",ad80588c56547cfcfc00e9080cce9920,c javascript matlab php sql firebase sql serve...
100,https://www.dice.com/jobs/detail/SWIFT-Messagi...,Mitchell Martin,"Contract Corp-To-Corp, Contract Independent, C...","Our client, one of the largest banking and fin...",Dice Id : mitchmar1,"Ny, NY",SWIFT Messaging Specialist,5 hours ago,Telecommuting not available|Travel not required,www.dice.com,"CSS, HTML, HTTP",eccbb9e529cc7fabd4418b8a3ef96645,c++ c++ vim use system disagree disagree agree...

In [11]:
final_data=final_data[["jobtitle","jobdescription","cleaned_skills"]]
final_data.head()

,jobtitle,jobdescription,cleaned_skills
96,(US)-Program Manager Senior,Responsible for managing one or more highly co...,java javascript lua php r sql react spark post...
97,"Business Analyst - Mortgage/Equiting Lending, ...",Job Description: Seeking a Business Process An...,c++ c java react .net core windows desktop clo...
98,DHMSM Operational Medicine Interface Developer,"TAD PGS, INC. is currently seeking a DHMSM Ope...",c java javascript python sql node.js .net core...
99,Information Technology Architect,"Our client, one of the world's leading profess...",c javascript matlab php sql firebase sql serve...
100,SWIFT Messaging Specialist,"Our client, one of the largest banking and fin...",c++ c++ vim use system disagree disagree agree...

In [12]:
final_data["combined"] = final_data["jobdescription"].str.cat(final_data["cleaned_skills"], sep=" ")
final_data.head()

,jobtitle,jobdescription,cleaned_skills,combined
96,(US)-Program Manager Senior,Responsible for managing one or more highly co...,java javascript lua php r sql react spark post...,Responsible for managing one or more highly co...
97,"Business Analyst - Mortgage/Equiting Lending, ...",Job Description: Seeking a Business Process An...,c++ c java react .net core windows desktop clo...,Job Description: Seeking a Business Process An...
98,DHMSM Operational Medicine Interface Developer,"TAD PGS, INC. is currently seeking a DHMSM Ope...",c java javascript python sql node.js .net core...,"TAD PGS, INC. is currently seeking a DHMSM Ope..."
99,Information Technology Architect,"Our client, one of the world's leading profess...",c javascript matlab php sql firebase sql serve...,"Our client, one of the world's leading profess..."
100,SWIFT Messaging Specialist,"Our client, one of the largest banking and fin...",c++ c++ vim use system disagree disagree agree...,"Our client, one of the largest banking and fin..."

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd
# TF-IDF Vectorizer
vectorizer = TfidfVectorizer()

# Vectorize both user skills and job descriptions
tfidfmatrix1 = vectorizer.fit_transform(final_data["combined"])

# Compute cosine similarity
similarity_matrix = cosine_similarity(tfidfmatrix1,tfidfmatrix1)

# Adding similarity scores to DataFrame
final_data['similarity_score'] = similarity_matrix.diagonal()

# Get top recommendations
recommendations = final_data.sort_values(by='similarity_score', ascending=False)
print(recommendations)

                                           jobtitle  \
15917                 Senior Java Developer (CSA 3)
15632             Enterprise BU - Android Developer
1988   Java Developer (Front & Backend Development)
8053                               Network Engineer
679                 Senior Business Process Analyst
...                                             ...
16187                System & Network Administrator
1875                                Network Support
1287         Sr. DevOps Engineer (Iconic Employer!)
1532        IT Security and Compliance Risk Advisor
1919                       IT Compliance Specialist

                                          jobdescription  \
15917  Title: Senior Java Developer (CSA 3)NetVision ...
15632   *** Please submit resume with posiion inquiry...
1988   Prudent Technologies and Consulting is a full-...
8053   Mid-level Network EngineerWe are looking for G...
679    OpportunityExciting Project Based and or caree...
...                                                  ...
16187  Provides network engineering, system administr...
1875   Position: Network SupportLocation: Frisco, Tex...
1287   Our iconic client is making it's most signific...
1532   EDUCATION: Bachelor’s Degree in Computer Scien...
1919   Apex Systems, the nation’s 2nd largest Informa...

                                          cleaned_skills  \
15917  c c++ c java javascript lua firebase mongodb p...
15632  javascript node.js amazon web services aws sub...
1988   groovy java javascript ruby scala sql vb.net s...
8053   groovy java sql mysql amazon web services aws ...
679    c haskell rust atom visual studio visual studi...
...                                                  ...
16187  c++ java javascript angularjs node.js mongodb ...
1875   vba windows desktop vb.net vba sql server wind...
1287   assembly c c javascript php python node.js cas...
1532   java javascript c node.js git agree strongly a...
1919   java javascript python node.js firebase androi...

                                                combined  similarity_score
15917  Title: Senior Java Developer (CSA 3)NetVision ...               1.0
15632   *** Please submit resume with posiion inquiry...               1.0
1988   Prudent Technologies and Consulting is a full-...               1.0
8053   Mid-level Network EngineerWe are looking for G...               1.0
679    OpportunityExciting Project Based and or caree...               1.0
...                                                  ...               ...
16187  Provides network engineering, system administr...               1.0
1875   Position: Network SupportLocation: Frisco, Tex...               1.0
1287   Our iconic client is making it's most signific...               1.0
1532   EDUCATION: Bachelor’s Degree in Computer Scien...               1.0
1919   Apex Systems, the nation’s 2nd largest Informa...               1.0

[3417 rows x 5 columns]

In [14]:
from rapidfuzz import process  # For approximate string matching

def recommendation(job_title, final_data, similarity_matrix, top_n=10, threshold=80):
    """
    Recommend jobs similar to a given job title with fallback to approximate matching.

    Parameters:
    - job_title: Input job title for recommendations.
    - final_data: DataFrame containing job descriptions, skills, and combined columns.
    - similarity_matrix: Precomputed cosine similarity matrix.
    - top_n: Number of recommendations to return.
    - threshold: Minimum similarity score for approximate matching.

    Returns:
    - List of recommended job titles.
    """
    # Ensure DataFrame index is reset and sequential
    final_data = final_data.reset_index(drop=True)

    # Create an indices mapping from job titles to DataFrame indices
    indices = pd.Series(final_data.index, index=final_data["jobtitle"]).to_dict()

    # Check if job title exists in indices
    if job_title in indices:
        idx = indices[job_title]
    else:
        # Approximate matching using rapidfuzz
        result = process.extractOne(job_title, indices.keys(), score_cutoff=threshold)
        if result:  # result contains (match, score, index)
            match, score, _ = result
            print(f"No exact match for '{job_title}'. Using closest match: '{match}' (score: {score})")
            idx = indices[match]
        else:
            raise KeyError(f"'{job_title}' not found and no close matches available.")

    # Get similarity scores for the job
    sim_scores = list(enumerate(similarity_matrix[idx]))

    # Sort scores in descending order (highest similarity first)
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Exclude the input job itself from recommendations
    sim_scores = [score for score in sim_scores if score[0] != idx]

    # Get indices of the top_n most similar jobs
    top_similar_indices = [i[0] for i in sim_scores[:top_n]]

    # Return the recommended job titles
    return final_data.iloc[top_similar_indices]["jobtitle"].tolist()

In [15]:
recommendations = recommendation("Senior C++,Senior Java Developer,Enterprise BU", final_data, similarity_matrix, top_n=10)
print("Top Recommendations:", recommendations)

No exact match for 'Senior C++,Senior Java Developer,Enterprise BU'. Using closest match: 'Java Developer' (score: 90.0)
Top Recommendations: ['Database Engineer/Architect', 'Principal JAVA Software Engineer (Cloud, Spring, full-stack, NoSQL..)', 'Java Software Engineer Lead', 'Front End Designer/Developer', 'Software Engineer - Full Stack Cloud product development', 'Web Developer - JavaScript expert!', 'Software Development Engineer', 'Principal Software Engineer', 'Android Developer with TDD experience', 'Cloud Engineer']